/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u07431666128
 */
public class JFrmTam_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmTam_Principal
     */
    public JFrmTam_Principal() {
        initComponents();
         setTitle("Sistema de Vendas de Roupas");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuTam_Usuarios = new javax.swing.JMenuItem();
        jMnuTam_Cliente = new javax.swing.JMenuItem();
        jMnuTam_Vendedor = new javax.swing.JMenuItem();
        jMnuTam_Produto = new javax.swing.JMenuItem();
        jMnuTam_Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuTam_Venda = new javax.swing.JMenuItem();
        jMnuTam_Vendas_Produtos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMnuTam_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-48 (1).png"))); // NOI18N
        jMnuTam_Usuarios.setText("Usuarios");
        jMnuTam_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_UsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuTam_Usuarios);

        jMnuTam_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-de-gênero-neutro-48.png"))); // NOI18N
        jMnuTam_Cliente.setText("Cliente");
        jMnuTam_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuTam_Cliente);

        jMnuTam_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-revendedor-48.png"))); // NOI18N
        jMnuTam_Vendedor.setText("Vendedor");
        jMnuTam_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_VendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuTam_Vendedor);

        jMnuTam_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-produto-48.png"))); // NOI18N
        jMnuTam_Produto.setText("Produto");
        jMnuTam_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_ProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuTam_Produto);

        jMnuTam_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-saída-de-incêndio-48.png"))); // NOI18N
        jMnuTam_Sair.setText("Sair");
        jMnuTam_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_SairActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuTam_Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMnuTam_Venda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-promoção-carrinho-de-compras-48.png"))); // NOI18N
        jMnuTam_Venda.setText("Venda");
        jMnuTam_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_VendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuTam_Venda);

        jMnuTam_Vendas_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuTam_Vendas_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sale-price-tag-48.png"))); // NOI18N
        jMnuTam_Vendas_Produtos.setText("Venda Produto");
        jMnuTam_Vendas_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuTam_Vendas_ProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuTam_Vendas_Produtos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuTam_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_UsuariosActionPerformed
        // TODO add your handling code here:
         Tam_JDlgUsuarios jDlgUsuarios = new  Tam_JDlgUsuarios(this,true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuTam_UsuariosActionPerformed

    private void jMnuTam_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_ClienteActionPerformed
        // TODO add your handling code here:
         Tam_JDlgCliente jDlgCliente = new Tam_JDlgCliente(this,true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMnuTam_ClienteActionPerformed

    private void jMnuTam_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_VendedorActionPerformed
        // TODO add your handling code here:
        JDlgTam_VendedorPesquisar jDlgVendedor = new JDlgTam_VendedorPesquisar(this,true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuTam_VendedorActionPerformed

    private void jMnuTam_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_ProdutoActionPerformed
        // TODO add your handling code here:
        Tam_JDlgProduto jDlgProduto = new Tam_JDlgProduto(this,true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jMnuTam_ProdutoActionPerformed

    private void jMnuTam_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_SairActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMnuTam_SairActionPerformed

    private void jMnuTam_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_VendaActionPerformed
        // TODO add your handling code here:
          Tam_JDlgVendas jDlgTam_Vendas = new Tam_JDlgVendas(this,true);
        jDlgTam_Vendas.setVisible(true);
    }//GEN-LAST:event_jMnuTam_VendaActionPerformed

    private void jMnuTam_Vendas_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuTam_Vendas_ProdutosActionPerformed
        // TODO add your handling code here:
         Tam_JDlgVendasProdutos jDlgTam_Vendas_Produtos = new Tam_JDlgVendasProdutos(this,true);
        jDlgTam_Vendas_Produtos.setVisible(true);
    }//GEN-LAST:event_jMnuTam_Vendas_ProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmTam_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmTam_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmTam_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmTam_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmTam_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuTam_Cliente;
    private javax.swing.JMenuItem jMnuTam_Produto;
    private javax.swing.JMenuItem jMnuTam_Sair;
    private javax.swing.JMenuItem jMnuTam_Usuarios;
    private javax.swing.JMenuItem jMnuTam_Venda;
    private javax.swing.JMenuItem jMnuTam_Vendas_Produtos;
    private javax.swing.JMenuItem jMnuTam_Vendedor;
    // End of variables declaration//GEN-END:variables
}
