/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.VendedorTam;
import dao.VendedorDAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Tam_Util;

/**
 *
 * @author u07431666128
 */
public class Tam_JDlgVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgTam_VendedorPesquisar
     */
    private boolean incluir;

    public Tam_JDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendedor");
        Tam_Util.habilitar(false, jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro, jTxtTam_Celular,
                jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade,
                jBtnTam_Confirmar, jBtnTam_Cancelar, jBtnTam_Excluir, jBtnTam_Alterar);
        try {
            MaskFormatter maskCpf = new MaskFormatter("###.###.###-##");
            jFmtTam_Cpf.setFormatterFactory(new DefaultFormatterFactory(maskCpf));

            MaskFormatter maskRg = new MaskFormatter("#########");
            jFmtTam_Rg.setFormatterFactory(new DefaultFormatterFactory(maskRg));

            MaskFormatter maskData = new MaskFormatter("##/##/####");
            jFmtTam_DataNascimento.setFormatterFactory(new DefaultFormatterFactory(maskData));

            MaskFormatter maskCep = new MaskFormatter("#####-###");
            jFmtTam_Cep.setFormatterFactory(new DefaultFormatterFactory(maskCep));

            MaskFormatter maskCnpj = new MaskFormatter("##.###.###/####-##");
            jFmtTam_Cnpj.setFormatterFactory(new DefaultFormatterFactory(maskCnpj));

        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtTam_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtTam_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtTam_Cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtTam_Rg = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtTam_DataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCboTam_Sexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTxtTam_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtTam_Cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtTam_Endereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtTam_Bairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtTam_Celular = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtTam_Nacionalidade = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCboTam_Escolaridade = new javax.swing.JComboBox<>();
        jBtnTam_Incluir = new javax.swing.JButton();
        jBtnTam_Alterar = new javax.swing.JButton();
        jBtnTam_Excluir = new javax.swing.JButton();
        jBtnTam_Confirmar = new javax.swing.JButton();
        jBtnTam_Cancelar = new javax.swing.JButton();
        jBtnTam_Pesquisar = new javax.swing.JButton();
        jFmtTam_Cep = new javax.swing.JFormattedTextField();
        jFmtTam_Cnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Sexo");

        jCboTam_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "feminino", "diádico", "intersexo ", "altersexo" }));

        jLabel7.setText("E-mail");

        jLabel8.setText("Cidade");

        jLabel9.setText("Endereço");

        jLabel10.setText("Bairro");

        jLabel11.setText("CEP");

        jLabel12.setText("Celular");

        jLabel13.setText("CNPJ");

        jLabel14.setText("Nacionalidade");

        jLabel15.setText("Escolaridade");

        jCboTam_Escolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto", "Ensino Médio Completo", "Educação Técnica", "Superior Incompleto", "Superior Completo", "Especialização", "Mestrado", "Doutorado" }));

        jBtnTam_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluirr.png"))); // NOI18N
        jBtnTam_Incluir.setText("Incluir");
        jBtnTam_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_IncluirActionPerformed(evt);
            }
        });

        jBtnTam_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterarr (1).png"))); // NOI18N
        jBtnTam_Alterar.setText("Alterar");
        jBtnTam_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_AlterarActionPerformed(evt);
            }
        });

        jBtnTam_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluirr.png"))); // NOI18N
        jBtnTam_Excluir.setText("Excluir");
        jBtnTam_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_ExcluirActionPerformed(evt);
            }
        });

        jBtnTam_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmarr.png"))); // NOI18N
        jBtnTam_Confirmar.setText("Confirmar");
        jBtnTam_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_ConfirmarActionPerformed(evt);
            }
        });

        jBtnTam_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caneclarr.png"))); // NOI18N
        jBtnTam_Cancelar.setText("Cancelar");
        jBtnTam_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_CancelarActionPerformed(evt);
            }
        });

        jBtnTam_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisarr.png"))); // NOI18N
        jBtnTam_Pesquisar.setText("Pesquisar");
        jBtnTam_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtTam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtTam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(311, 311, 311)
                        .addComponent(jLabel4)
                        .addGap(233, 233, 233)
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmtTam_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jFmtTam_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jFmtTam_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCboTam_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(293, 293, 293)
                        .addComponent(jLabel11)
                        .addGap(232, 232, 232)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtTam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jFmtTam_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jTxtTam_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel10)
                        .addGap(393, 393, 393)
                        .addComponent(jLabel12)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtTam_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtTam_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jTxtTam_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFmtTam_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtTam_Nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jCboTam_Escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnTam_Incluir)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnTam_Alterar)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnTam_Excluir)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnTam_Confirmar)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnTam_Cancelar)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnTam_Pesquisar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jTxtTam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jTxtTam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jFmtTam_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jFmtTam_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jFmtTam_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCboTam_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTam_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTam_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtTam_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtTam_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTxtTam_Nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCboTam_Escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnTam_Incluir)
                    .addComponent(jBtnTam_Alterar)
                    .addComponent(jBtnTam_Excluir)
                    .addComponent(jBtnTam_Confirmar)
                    .addComponent(jBtnTam_Cancelar)
                    .addComponent(jBtnTam_Pesquisar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTam_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_IncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Tam_Util.habilitar(true, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade,
                jBtnTam_Confirmar, jBtnTam_Cancelar, jTxtTam_Codigo);
        Tam_Util.habilitar(false, jBtnTam_Incluir, jBtnTam_Alterar, jBtnTam_Excluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade);
        jTxtTam_Codigo.grabFocus();
    }//GEN-LAST:event_jBtnTam_IncluirActionPerformed

    private void jBtnTam_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_AlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Tam_Util.habilitar(true, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade,
                jBtnTam_Confirmar, jBtnTam_Cancelar);
        Tam_Util.habilitar(false, jBtnTam_Incluir, jBtnTam_Alterar, jBtnTam_Excluir, jBtnTam_Pesquisar);
        jTxtTam_Nome.grabFocus();
    }//GEN-LAST:event_jBtnTam_AlterarActionPerformed

    private void jBtnTam_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Tam_Util.perguntar("Deseja realmente excluir o registro?")) {
            VendedorDAO dao = new VendedorDAO();
            try {
                dao.delete(viewBean());
                Tam_Util.mensagem("Registro excluído com sucesso!");
                Tam_Util.limpar(jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                        jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                        jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                        jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade);
                Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Pesquisar);
                Tam_Util.habilitar(false, jBtnTam_Alterar, jBtnTam_Excluir);
            } catch (ParseException ex) {
                Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Tam_Util.mensagem("Exclusão cancelada.");
        }
    }//GEN-LAST:event_jBtnTam_ExcluirActionPerformed

    private void jBtnTam_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_ConfirmarActionPerformed
        // TODO add your handling code here:
        VendedorDAO dao = new VendedorDAO();
        try {
            VendedorTam vendedor = viewBean();
            if (incluir) {
                dao.insert(vendedor);
                Tam_Util.mensagem("Registro incluído com sucesso!");
            } else {
                dao.update(vendedor);
                Tam_Util.mensagem("Registro alterado com sucesso!");
            }
        } catch (ParseException ex) {
            Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tam_Util.habilitar(false, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade,
                jBtnTam_Confirmar, jBtnTam_Cancelar, jTxtTam_Codigo, jBtnTam_Alterar, jBtnTam_Excluir);
        Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade);

    }//GEN-LAST:event_jBtnTam_ConfirmarActionPerformed

    private void jBtnTam_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_CancelarActionPerformed
        // TODO add your handling code here:
        Tam_Util.habilitar(false, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade,
                jBtnTam_Confirmar, jBtnTam_Cancelar);
        Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_Rg, jFmtTam_DataNascimento, jCboTam_Sexo, jTxtTam_Email,
                jTxtTam_Cidade, jFmtTam_Cep, jTxtTam_Endereco, jTxtTam_Bairro,
                jTxtTam_Celular, jFmtTam_Cnpj, jTxtTam_Nacionalidade, jCboTam_Escolaridade);
    }//GEN-LAST:event_jBtnTam_CancelarActionPerformed

    private void jBtnTam_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgTam_VendedorPesquisar jDlgPesquisar = new JDlgTam_VendedorPesquisar(null, true);
        jDlgPesquisar.setTelaAnterior(this);
        jDlgPesquisar.setVisible(true);
        Tam_Util.habilitar(true, jBtnTam_Alterar, jBtnTam_Excluir);
    }//GEN-LAST:event_jBtnTam_PesquisarActionPerformed

    public void beanView(VendedorTam vendedor) {
        jTxtTam_Codigo.setText(Tam_Util.intToString(vendedor.getIdvendedorTam()));
        jTxtTam_Nome.setText(vendedor.getNomeTam());
        jFmtTam_Cpf.setText(vendedor.getCpfTam());
        jFmtTam_Rg.setText(vendedor.getRgTam());
        jFmtTam_DataNascimento.setText(Tam_Util.dateToStr(vendedor.getDataNascTam()));
        jCboTam_Sexo.setSelectedIndex(vendedor.getSexoTam());
        jTxtTam_Email.setText(vendedor.getEmailTam());
        jTxtTam_Cidade.setText(vendedor.getCidadeTam());
        jFmtTam_Cep.setText(vendedor.getCepTam());
        jTxtTam_Endereco.setText(vendedor.getEnderecoTam());
        jTxtTam_Bairro.setText(vendedor.getBairroTam());
        jTxtTam_Celular.setText(vendedor.getCelularTam());
        jFmtTam_Cnpj.setText(vendedor.getCnpjTam());
        jTxtTam_Nacionalidade.setText(vendedor.getNacionalidadeTam());
        jCboTam_Escolaridade.setSelectedIndex(vendedor.getEscolaridade());
    }

    public VendedorTam viewBean() throws ParseException {
        VendedorTam vendedor = new VendedorTam();
        vendedor.setIdvendedorTam(Tam_Util.strToInt(jTxtTam_Codigo.getText()));
        vendedor.setNomeTam(jTxtTam_Nome.getText());
        vendedor.setCpfTam(jFmtTam_Cpf.getText());
        vendedor.setRgTam(jFmtTam_Rg.getText());
        vendedor.setDataNascTam(Tam_Util.strToDate(jFmtTam_DataNascimento.getText()));
        vendedor.setSexoTam(jCboTam_Sexo.getSelectedIndex());
        vendedor.setEmailTam(jTxtTam_Email.getText());
        vendedor.setCidadeTam(jTxtTam_Cidade.getText());
        vendedor.setCepTam(jFmtTam_Cep.getText());
        vendedor.setEnderecoTam(jTxtTam_Endereco.getText());
        vendedor.setBairroTam(jTxtTam_Bairro.getText());
        vendedor.setCelularTam(jTxtTam_Celular.getText());
        vendedor.setCnpjTam(jFmtTam_Cnpj.getText());
        vendedor.setNacionalidadeTam(jTxtTam_Nacionalidade.getText());
        vendedor.setEscolaridade(jCboTam_Escolaridade.getSelectedIndex());
        return vendedor;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tam_JDlgVendedor dialog = new Tam_JDlgVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnTam_Alterar;
    private javax.swing.JButton jBtnTam_Cancelar;
    private javax.swing.JButton jBtnTam_Confirmar;
    private javax.swing.JButton jBtnTam_Excluir;
    private javax.swing.JButton jBtnTam_Incluir;
    private javax.swing.JButton jBtnTam_Pesquisar;
    private javax.swing.JComboBox<String> jCboTam_Escolaridade;
    private javax.swing.JComboBox<String> jCboTam_Sexo;
    private javax.swing.JFormattedTextField jFmtTam_Cep;
    private javax.swing.JFormattedTextField jFmtTam_Cnpj;
    private javax.swing.JFormattedTextField jFmtTam_Cpf;
    private javax.swing.JFormattedTextField jFmtTam_DataNascimento;
    private javax.swing.JFormattedTextField jFmtTam_Rg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtTam_Bairro;
    private javax.swing.JTextField jTxtTam_Celular;
    private javax.swing.JTextField jTxtTam_Cidade;
    private javax.swing.JTextField jTxtTam_Codigo;
    private javax.swing.JTextField jTxtTam_Email;
    private javax.swing.JTextField jTxtTam_Endereco;
    private javax.swing.JTextField jTxtTam_Nacionalidade;
    private javax.swing.JTextField jTxtTam_Nome;
    // End of variables declaration//GEN-END:variables
}
