/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.ClienteTam;
import dao.ClientesDAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Tam_Util;

/**
 *
 * @author u07431666128
 */
public class Tam_JDlgCliente extends javax.swing.JDialog {

    /**
     * Creates new form Tam_JDlgCliente
     */
    private boolean incluir;
    public Tam_JDlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Clienteee");
        Tam_Util.habilitar(false, jTxtTam_Nome, jFmtTam_Cpf,jTxtTam_Codigo,
                jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao, jBtnTam_Confirmar, jBtnTam_Cancelar,
                jBtnTam_Alterar ,jBtnTam_Excluir );

        try {
            MaskFormatter maskCpf = new MaskFormatter("###.###.###-##");
            jFmtTam_Cpf.setFormatterFactory(new DefaultFormatterFactory(maskCpf));

            MaskFormatter maskData = new MaskFormatter("##/##/####");
            jFmtTam_DataNascimento.setFormatterFactory(new DefaultFormatterFactory(maskData));

            MaskFormatter maskRg = new MaskFormatter("#########");
            jFmtTam_Rg.setFormatterFactory(new DefaultFormatterFactory(maskRg));

          

        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtTam_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtTam_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtTam_Cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtTam_DataNascimento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtTam_Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFmtTam_Rg = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jCboTam_Sexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTxtTam_Cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtTam_Nacionalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtTam_Endereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtTam_Bairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtTam_Celular = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCboTam_EstadoCivil = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTxtTam_Profissao = new javax.swing.JTextField();
        jBtnTam_Incluir = new javax.swing.JButton();
        jBtnTam_Alterar = new javax.swing.JButton();
        jBtnTam_Excluir = new javax.swing.JButton();
        jBtnTam_Confirmar = new javax.swing.JButton();
        jBtnTam_Cancelar = new javax.swing.JButton();
        jBtnTam_Pesquisar = new javax.swing.JButton();
        jFmtTam_N = new javax.swing.JFormattedTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("E-mail");

        jLabel6.setText("RG");

        jLabel7.setText("Sexo");

        jCboTam_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "feminino", "diádico", "intersexo ", "altersexo" }));

        jLabel8.setText("Cidade");

        jLabel9.setText("Nacionalidade");

        jLabel10.setText("Endereço");

        jLabel11.setText("Bairro");

        jLabel12.setText("N°");

        jLabel13.setText("Celular");

        jLabel14.setText("Estado Civil");

        jCboTam_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Separado ", "Divorciado", "Viúvo" }));

        jLabel15.setText("Profissão");

        jBtnTam_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluirr.png"))); // NOI18N
        jBtnTam_Incluir.setText("Incluir");
        jBtnTam_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_IncluirActionPerformed(evt);
            }
        });

        jBtnTam_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterarr (1).png"))); // NOI18N
        jBtnTam_Alterar.setText("Alterar");
        jBtnTam_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_AlterarActionPerformed(evt);
            }
        });

        jBtnTam_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluirr.png"))); // NOI18N
        jBtnTam_Excluir.setText("Excluir");
        jBtnTam_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_ExcluirActionPerformed(evt);
            }
        });

        jBtnTam_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmarr.png"))); // NOI18N
        jBtnTam_Confirmar.setText("Confirmar");
        jBtnTam_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_ConfirmarActionPerformed(evt);
            }
        });

        jBtnTam_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caneclarr.png"))); // NOI18N
        jBtnTam_Cancelar.setText("Cancelar");
        jBtnTam_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_CancelarActionPerformed(evt);
            }
        });

        jBtnTam_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisarr.png"))); // NOI18N
        jBtnTam_Pesquisar.setText("Pesquisar");
        jBtnTam_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTam_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jCboTam_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTam_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTam_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTam_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTam_Confirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTam_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTam_Pesquisar))
                            .addComponent(jTxtTam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFmtTam_Rg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFmtTam_Cpf, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtTam_Endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtTam_Cidade, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel10))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtTam_Bairro)
                                            .addComponent(jTxtTam_Profissao)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jTxtTam_Nacionalidade, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jFmtTam_DataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCboTam_Sexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel9)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel7)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addComponent(jLabel12)
                                                        .addGap(58, 58, 58))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jFmtTam_N, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jTxtTam_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel5)
                                            .addComponent(jTxtTam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(304, 304, 304))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtTam_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTam_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtTam_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboTam_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTam_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTam_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTam_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboTam_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTam_Profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTam_Incluir)
                    .addComponent(jBtnTam_Alterar)
                    .addComponent(jBtnTam_Excluir)
                    .addComponent(jBtnTam_Confirmar)
                    .addComponent(jBtnTam_Cancelar)
                    .addComponent(jBtnTam_Pesquisar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTam_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_IncluirActionPerformed
        // TODO add your handling code here:
        Tam_Util.habilitar(true,
                jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao, jBtnTam_Confirmar, jBtnTam_Cancelar, jTxtTam_Codigo
        );
        Tam_Util.habilitar(false, jBtnTam_Incluir, jBtnTam_Alterar, jBtnTam_Excluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(
                jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao
        );
        jTxtTam_Codigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnTam_IncluirActionPerformed

    private void jBtnTam_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_AlterarActionPerformed
        // TODO add your handling code here:
        Tam_Util.habilitar(true,
                jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao, jBtnTam_Confirmar, jBtnTam_Cancelar
        );
        Tam_Util.habilitar(false, jBtnTam_Incluir, jBtnTam_Alterar, jBtnTam_Excluir, jBtnTam_Pesquisar, jTxtTam_Codigo);
        jTxtTam_Nome.grabFocus();
        incluir = false;
    }//GEN-LAST:event_jBtnTam_AlterarActionPerformed

    private void jBtnTam_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Tam_Util.perguntar("Deseja realmente excluir o registro?")) {
            Tam_Util.mensagem("Registro excluído com sucesso!");
            ClientesDAO dao = new ClientesDAO();
            try {
                dao.delete(viewBean());
                Tam_Util.limpar(
                        jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, 
                        jTxtTam_Email, jFmtTam_Rg,
                        jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                        jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                        jCboTam_EstadoCivil, jTxtTam_Profissao
                );
                Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Pesquisar);
                Tam_Util.habilitar(false, jBtnTam_Alterar, jBtnTam_Excluir);
            } catch (ParseException ex) {
                Logger.getLogger(Tam_JDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Tam_Util.mensagem("Exclusão cancelada.");
        }
    }//GEN-LAST:event_jBtnTam_ExcluirActionPerformed

    private void jBtnTam_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_ConfirmarActionPerformed
        // TODO add your handling code here:
        ClientesDAO dao = new ClientesDAO();
        try {
            ClienteTam cliente = viewBean();
            if (cliente.getIdclienteTam() == 0) {
                Tam_Util.mensagem("Por favor, informe um ID válido!");
            } else if (incluir) {
                dao.insert(cliente);
            } else {
                dao.update(cliente);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Tam_JDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tam_Util.habilitar(false,
                jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, jTxtTam_Email, 
                jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao, jBtnTam_Confirmar, jBtnTam_Cancelar, jBtnTam_Alterar, jBtnTam_Excluir
        );
        Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Alterar, jBtnTam_Excluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(
                jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf, jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao
        );
 
    }//GEN-LAST:event_jBtnTam_ConfirmarActionPerformed

    private void jBtnTam_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_CancelarActionPerformed
        // TODO add your handling code here:
        Tam_Util.habilitar(false, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade, jTxtTam_Codigo,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao, jBtnTam_Confirmar, jBtnTam_Cancelar, jBtnTam_Alterar, jBtnTam_Excluir);
        Tam_Util.habilitar(true, jBtnTam_Incluir, jBtnTam_Pesquisar);
        Tam_Util.limpar(jTxtTam_Codigo, jTxtTam_Nome, jFmtTam_Cpf,
                jFmtTam_DataNascimento, jTxtTam_Email, jFmtTam_Rg,
                jCboTam_Sexo, jTxtTam_Cidade, jTxtTam_Nacionalidade,
                jTxtTam_Endereco, jTxtTam_Bairro, jFmtTam_N, jTxtTam_Celular,
                jCboTam_EstadoCivil, jTxtTam_Profissao);
    }//GEN-LAST:event_jBtnTam_CancelarActionPerformed

    private void jBtnTam_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTam_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgTam_ClientePesquisar jDlgClientePesquisar = new JDlgTam_ClientePesquisar(null, true);
        jDlgClientePesquisar.setTelaAnterior(this);
        jDlgClientePesquisar.setVisible(true);

        Tam_Util.habilitar(true, jBtnTam_Alterar, jBtnTam_Excluir);

    }//GEN-LAST:event_jBtnTam_PesquisarActionPerformed
    public void beanView(ClienteTam cliente) {
        jTxtTam_Codigo.setText(Tam_Util.intToString(cliente.getIdclienteTam()));
        jTxtTam_Nome.setText(cliente.getNomeTam());
        jFmtTam_Cpf.setText(cliente.getCpfTam());
        jFmtTam_Rg.setText(cliente.getRg());
        jFmtTam_DataNascimento.setText(Tam_Util.dateToStr(cliente.getDataNascTam()));
        jCboTam_Sexo.setSelectedIndex(Tam_Util.strToInt(cliente.getSexoTam()) );
        jTxtTam_Email.setText(cliente.getEmailTam());
        jTxtTam_Cidade.setText(cliente.getCidadeTam());
        jTxtTam_Nacionalidade.setText(cliente.getNacionalidadeTam());
        jTxtTam_Endereco.setText(cliente.getEnderecoTam());
        jTxtTam_Bairro.setText(cliente.getBairroTam());
        jFmtTam_N.setText(cliente.getNumeroTam());
        jTxtTam_Celular.setText(cliente.getCelularTam());
        jCboTam_EstadoCivil.setSelectedIndex(cliente.getEstadoCivilTam());
        jTxtTam_Profissao.setText(cliente.getProfissaoTam());
    }

    public ClienteTam viewBean() throws ParseException {
        ClienteTam cliente = new ClienteTam();
        cliente.setIdclienteTam(Tam_Util.strToInt(jTxtTam_Codigo.getText()));
        cliente.setNomeTam(jTxtTam_Nome.getText());
        cliente.setCpfTam(jFmtTam_Cpf.getText());
        cliente.setRg(jFmtTam_Rg.getText());
        cliente.setDataNascTam(Tam_Util.strToDate(jFmtTam_DataNascimento.getText()));
        cliente.setSexoTam(Tam_Util.intToString(jCboTam_Sexo.getSelectedIndex()) );
        cliente.setEmailTam(jTxtTam_Email.getText());
        cliente.setCidadeTam(jTxtTam_Cidade.getText());
        cliente.setNacionalidadeTam(jTxtTam_Nacionalidade.getText());
        cliente.setEnderecoTam(jTxtTam_Endereco.getText());
        cliente.setBairroTam(jTxtTam_Bairro.getText());
        cliente.setNumeroTam(jFmtTam_N.getText());
        cliente.setCelularTam(jTxtTam_Celular.getText());
        cliente.setEstadoCivilTam(jCboTam_EstadoCivil.getSelectedIndex());
        cliente.setProfissaoTam(jTxtTam_Profissao.getText());
        return cliente;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tam_JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tam_JDlgCliente dialog = new Tam_JDlgCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnTam_Alterar;
    private javax.swing.JButton jBtnTam_Cancelar;
    private javax.swing.JButton jBtnTam_Confirmar;
    private javax.swing.JButton jBtnTam_Excluir;
    private javax.swing.JButton jBtnTam_Incluir;
    private javax.swing.JButton jBtnTam_Pesquisar;
    private javax.swing.JComboBox<String> jCboTam_EstadoCivil;
    private javax.swing.JComboBox<String> jCboTam_Sexo;
    private javax.swing.JFormattedTextField jFmtTam_Cpf;
    private javax.swing.JFormattedTextField jFmtTam_DataNascimento;
    private javax.swing.JFormattedTextField jFmtTam_N;
    private javax.swing.JFormattedTextField jFmtTam_Rg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTxtTam_Bairro;
    private javax.swing.JTextField jTxtTam_Celular;
    private javax.swing.JTextField jTxtTam_Cidade;
    private javax.swing.JTextField jTxtTam_Codigo;
    private javax.swing.JTextField jTxtTam_Email;
    private javax.swing.JTextField jTxtTam_Endereco;
    private javax.swing.JTextField jTxtTam_Nacionalidade;
    private javax.swing.JTextField jTxtTam_Nome;
    private javax.swing.JTextField jTxtTam_Profissao;
    // End of variables declaration//GEN-END:variables
}
