package bean;
// Generated Oct 22, 2025 11:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteTam generated by hbm2java
 */
@Entity
@Table(name="cliente_tam"
    ,catalog="db_thais_oliveira"
)
public class ClienteTam  implements java.io.Serializable {


     private int idclienteTam;
     private String nomeTam;
     private String cpfTam;
     private String rg;
     private Date dataNascTam;
     private String sexoTam;
     private String emailTam;
     private String cidadeTam;
     private String nacionalidadeTam;
     private String enderecoTam;
     private String bairroTam;
     private String numeroTam;
     private String celularTam;
     private int estadoCivilTam;
     private String profissaoTam;
 

    public ClienteTam() {
    }

	
    public ClienteTam(int idclienteTam, String nomeTam, String cpfTam, String rg, Date dataNascTam, String sexoTam, String emailTam, String cidadeTam, String nacionalidadeTam, String enderecoTam, String bairroTam, String numeroTam, String celularTam, int estadoCivilTam, String profissaoTam) {
        this.idclienteTam = idclienteTam;
        this.nomeTam = nomeTam;
        this.cpfTam = cpfTam;
        this.rg = rg;
        this.dataNascTam = dataNascTam;
        this.sexoTam = sexoTam;
        this.emailTam = emailTam;
        this.cidadeTam = cidadeTam;
        this.nacionalidadeTam = nacionalidadeTam;
        this.enderecoTam = enderecoTam;
        this.bairroTam = bairroTam;
        this.numeroTam = numeroTam;
        this.celularTam = celularTam;
        this.estadoCivilTam = estadoCivilTam;
        this.profissaoTam = profissaoTam;
    }

   
     @Id 

    
    @Column(name="idcliente_tam", unique=true, nullable=false)
    public int getIdclienteTam() {
        return this.idclienteTam;
    }
    
    public void setIdclienteTam(int idclienteTam) {
        this.idclienteTam = idclienteTam;
    }

    
    @Column(name="nome_tam", nullable=false, length=50)
    public String getNomeTam() {
        return this.nomeTam;
    }
    
    public void setNomeTam(String nomeTam) {
        this.nomeTam = nomeTam;
    }

    
    @Column(name="cpf_tam", nullable=false, length=14)
    public String getCpfTam() {
        return this.cpfTam;
    }
    
    public void setCpfTam(String cpfTam) {
        this.cpfTam = cpfTam;
    }

    
    @Column(name="rg", nullable=false, length=10)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc_tam", nullable=false, length=10)
    public Date getDataNascTam() {
        return this.dataNascTam;
    }
    
    public void setDataNascTam(Date dataNascTam) {
        this.dataNascTam = dataNascTam;
    }

    
    @Column(name="sexo_tam", nullable=false, length=1)
    public String getSexoTam() {
        return this.sexoTam;
    }
    
    public void setSexoTam(String sexoTam) {
        this.sexoTam = sexoTam;
    }

    
    @Column(name="email_tam", nullable=false, length=50)
    public String getEmailTam() {
        return this.emailTam;
    }
    
    public void setEmailTam(String emailTam) {
        this.emailTam = emailTam;
    }

    
    @Column(name="cidade_tam", nullable=false, length=50)
    public String getCidadeTam() {
        return this.cidadeTam;
    }
    
    public void setCidadeTam(String cidadeTam) {
        this.cidadeTam = cidadeTam;
    }

    
    @Column(name="nacionalidade_tam", nullable=false, length=30)
    public String getNacionalidadeTam() {
        return this.nacionalidadeTam;
    }
    
    public void setNacionalidadeTam(String nacionalidadeTam) {
        this.nacionalidadeTam = nacionalidadeTam;
    }

    
    @Column(name="endereco_tam", nullable=false, length=50)
    public String getEnderecoTam() {
        return this.enderecoTam;
    }
    
    public void setEnderecoTam(String enderecoTam) {
        this.enderecoTam = enderecoTam;
    }

    
    @Column(name="bairro_tam", nullable=false, length=30)
    public String getBairroTam() {
        return this.bairroTam;
    }
    
    public void setBairroTam(String bairroTam) {
        this.bairroTam = bairroTam;
    }

    
    @Column(name="numero_tam", nullable=false, length=10)
    public String getNumeroTam() {
        return this.numeroTam;
    }
    
    public void setNumeroTam(String numeroTam) {
        this.numeroTam = numeroTam;
    }

    
    @Column(name="celular_tam", nullable=false, length=9)
    public String getCelularTam() {
        return this.celularTam;
    }
    
    public void setCelularTam(String celularTam) {
        this.celularTam = celularTam;
    }

    
    @Column(name="estadoCivil_tam", nullable=false)
    public int getEstadoCivilTam() {
        return this.estadoCivilTam;
    }
    
    public void setEstadoCivilTam(int estadoCivilTam) {
        this.estadoCivilTam = estadoCivilTam;
    }

    
    @Column(name="profissao_tam", nullable=false, length=50)
    public String getProfissaoTam() {
        return this.profissaoTam;
    }
    
    public void setProfissaoTam(String profissaoTam) {
        this.profissaoTam = profissaoTam;
    }





}


