package bean;
// Generated Oct 22, 2025 11:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdutoTam generated by hbm2java
 */
@Entity
@Table(name="produto_tam"
    ,catalog="db_thais_oliveira"
)
public class ProdutoTam  implements java.io.Serializable {


     private int idprodutoTam;
     private String nomeTam;
     private int categoriaProdutoTam;
     private int quantidadeProdutoTam;
     private String precoUnitarioTam;
     private String descricaoProdutoTam;
     private Date dataFabricacaoTam;
 

    public ProdutoTam() {
    }

	
    public ProdutoTam(int idprodutoTam, String nomeTam, int categoriaProdutoTam, int quantidadeProdutoTam, String precoUnitarioTam, String descricaoProdutoTam, Date dataFabricacaoTam) {
        this.idprodutoTam = idprodutoTam;
        this.nomeTam = nomeTam;
        this.categoriaProdutoTam = categoriaProdutoTam;
        this.quantidadeProdutoTam = quantidadeProdutoTam;
        this.precoUnitarioTam = precoUnitarioTam;
        this.descricaoProdutoTam = descricaoProdutoTam;
        this.dataFabricacaoTam = dataFabricacaoTam;
    }

   
     @Id 

    
    @Column(name="idproduto_tam", unique=true, nullable=false)
    public int getIdprodutoTam() {
        return this.idprodutoTam;
    }
    
    public void setIdprodutoTam(int idprodutoTam) {
        this.idprodutoTam = idprodutoTam;
    }

    
    @Column(name="nome_tam", nullable=false, length=50)
    public String getNomeTam() {
        return this.nomeTam;
    }
    
    public void setNomeTam(String nomeTam) {
        this.nomeTam = nomeTam;
    }

    
    @Column(name="categoriaProduto_tam", nullable=false)
    public int getCategoriaProdutoTam() {
        return this.categoriaProdutoTam;
    }
    
    public void setCategoriaProdutoTam(int categoriaProdutoTam) {
        this.categoriaProdutoTam = categoriaProdutoTam;
    }

    
    @Column(name="quantidadeProduto_tam", nullable=false)
    public int getQuantidadeProdutoTam() {
        return this.quantidadeProdutoTam;
    }
    
    public void setQuantidadeProdutoTam(int quantidadeProdutoTam) {
        this.quantidadeProdutoTam = quantidadeProdutoTam;
    }

    
    @Column(name="precoUnitario_tam", nullable=false, length=10)
    public String getPrecoUnitarioTam() {
        return this.precoUnitarioTam;
    }
    
    public void setPrecoUnitarioTam(String precoUnitarioTam) {
        this.precoUnitarioTam = precoUnitarioTam;
    }

    
    @Column(name="descricaoProduto_tam", nullable=false, length=150)
    public String getDescricaoProdutoTam() {
        return this.descricaoProdutoTam;
    }
    
    public void setDescricaoProdutoTam(String descricaoProdutoTam) {
        this.descricaoProdutoTam = descricaoProdutoTam;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataFabricacao_tam", nullable=false, length=10)
    public Date getDataFabricacaoTam() {
        return this.dataFabricacaoTam;
    }
    
    public void setDataFabricacaoTam(Date dataFabricacaoTam) {
        this.dataFabricacaoTam = dataFabricacaoTam;
    }





}


