package bean;
// Generated Oct 22, 2025 11:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorTam generated by hbm2java
 */
@Entity
@Table(name="vendedor_tam"
    ,catalog="db_thais_oliveira"
)
public class VendedorTam  implements java.io.Serializable {


     private int idvendedorTam;
     private String nomeTam;
     private String cpfTam;
     private String rgTam;
     private Date dataNascTam;
     private int sexoTam;
     private String emailTam;
     private String cidadeTam;
     private String nacionalidadeTam;
     private String enderecoTam;
     private String bairroTam;
     private String cepTam;
     private String celularTam;
     private String cnpjTam;
     private int escolaridade;

    public VendedorTam() {
    }

    public VendedorTam(int idvendedorTam, String nomeTam, String cpfTam, String rgTam, Date dataNascTam, int sexoTam, String emailTam, String cidadeTam, String nacionalidadeTam, String enderecoTam, String bairroTam, String cepTam, String celularTam, String cnpjTam, int escolaridade) {
       this.idvendedorTam = idvendedorTam;
       this.nomeTam = nomeTam;
       this.cpfTam = cpfTam;
       this.rgTam = rgTam;
       this.dataNascTam = dataNascTam;
       this.sexoTam = sexoTam;
       this.emailTam = emailTam;
       this.cidadeTam = cidadeTam;
       this.nacionalidadeTam = nacionalidadeTam;
       this.enderecoTam = enderecoTam;
       this.bairroTam = bairroTam;
       this.cepTam = cepTam;
       this.celularTam = celularTam;
       this.cnpjTam = cnpjTam;
       this.escolaridade = escolaridade;
    }
   
     @Id 

    
    @Column(name="idvendedor_tam", unique=true, nullable=false)
    public int getIdvendedorTam() {
        return this.idvendedorTam;
    }
    
    public void setIdvendedorTam(int idvendedorTam) {
        this.idvendedorTam = idvendedorTam;
    }

    
    @Column(name="nome_tam", nullable=false, length=50)
    public String getNomeTam() {
        return this.nomeTam;
    }
    
    public void setNomeTam(String nomeTam) {
        this.nomeTam = nomeTam;
    }

    
    @Column(name="cpf_tam", nullable=false, length=14)
    public String getCpfTam() {
        return this.cpfTam;
    }
    
    public void setCpfTam(String cpfTam) {
        this.cpfTam = cpfTam;
    }

    
    @Column(name="rg_tam", nullable=false, length=10)
    public String getRgTam() {
        return this.rgTam;
    }
    
    public void setRgTam(String rgTam) {
        this.rgTam = rgTam;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc_tam", nullable=false, length=10)
    public Date getDataNascTam() {
        return this.dataNascTam;
    }
    
    public void setDataNascTam(Date dataNascTam) {
        this.dataNascTam = dataNascTam;
    }

    
    @Column(name="sexo_tam", nullable=false)
    public int getSexoTam() {
        return this.sexoTam;
    }
    
    public void setSexoTam(int sexoTam) {
        this.sexoTam = sexoTam;
    }

    
    @Column(name="email_tam", nullable=false, length=50)
    public String getEmailTam() {
        return this.emailTam;
    }
    
    public void setEmailTam(String emailTam) {
        this.emailTam = emailTam;
    }

    
    @Column(name="cidade_tam", nullable=false, length=50)
    public String getCidadeTam() {
        return this.cidadeTam;
    }
    
    public void setCidadeTam(String cidadeTam) {
        this.cidadeTam = cidadeTam;
    }

    
    @Column(name="nacionalidade_tam", nullable=false, length=30)
    public String getNacionalidadeTam() {
        return this.nacionalidadeTam;
    }
    
    public void setNacionalidadeTam(String nacionalidadeTam) {
        this.nacionalidadeTam = nacionalidadeTam;
    }

    
    @Column(name="endereco_tam", nullable=false, length=50)
    public String getEnderecoTam() {
        return this.enderecoTam;
    }
    
    public void setEnderecoTam(String enderecoTam) {
        this.enderecoTam = enderecoTam;
    }

    
    @Column(name="bairro_tam", nullable=false, length=30)
    public String getBairroTam() {
        return this.bairroTam;
    }
    
    public void setBairroTam(String bairroTam) {
        this.bairroTam = bairroTam;
    }

    
    @Column(name="cep_tam", nullable=false, length=15)
    public String getCepTam() {
        return this.cepTam;
    }
    
    public void setCepTam(String cepTam) {
        this.cepTam = cepTam;
    }

    
    @Column(name="celular_tam", nullable=false, length=9)
    public String getCelularTam() {
        return this.celularTam;
    }
    
    public void setCelularTam(String celularTam) {
        this.celularTam = celularTam;
    }

    
    @Column(name="cnpj_tam", nullable=false, length=45)
    public String getCnpjTam() {
        return this.cnpjTam;
    }
    
    public void setCnpjTam(String cnpjTam) {
        this.cnpjTam = cnpjTam;
    }

    
    @Column(name="escolaridade", nullable=false)
    public int getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(int escolaridade) {
        this.escolaridade = escolaridade;
    }
    @Override
    public String toString() {
        return this.nomeTam;
    }



}


