package bean;
// Generated Oct 22, 2025 11:08:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutosTam generated by hbm2java
 */
@Entity
@Table(name="vendas_produtos_tam"
    ,catalog="db_thais_oliveira"
)
public class VendasProdutosTam  implements java.io.Serializable {


     private int idVendaProdutoTam;
     private ProdutoTam produtoTam;
     private VendasTam vendasTam;
     private String quantidadeProdutoTam;
     private String valorUnitarioTam;
     private int formaPagamentoTam;
     private String descontoTam;
     private String tipoDescontoTam;

    public VendasProdutosTam() {
    }

    public VendasProdutosTam(int idVendaProdutoTam, ProdutoTam produtoTam, VendasTam vendasTam, String quantidadeProdutoTam, String valorUnitarioTam, int formaPagamentoTam, String descontoTam, String tipoDescontoTam) {
       this.idVendaProdutoTam = idVendaProdutoTam;
       this.produtoTam = produtoTam;
       this.vendasTam = vendasTam;
       this.quantidadeProdutoTam = quantidadeProdutoTam;
       this.valorUnitarioTam = valorUnitarioTam;
       this.formaPagamentoTam = formaPagamentoTam;
       this.descontoTam = descontoTam;
       this.tipoDescontoTam = tipoDescontoTam;
    }
   
     @Id 

    
    @Column(name="idVenda_produto_tam", unique=true, nullable=false)
    public int getIdVendaProdutoTam() {
        return this.idVendaProdutoTam;
    }
    
    public void setIdVendaProdutoTam(int idVendaProdutoTam) {
        this.idVendaProdutoTam = idVendaProdutoTam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_idProduto_tam", nullable=false)
    public ProdutoTam getProdutoTam() {
        return this.produtoTam;
    }
    
    public void setProdutoTam(ProdutoTam produtoTam) {
        this.produtoTam = produtoTam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_idVenda_tam", nullable=false)
    public VendasTam getVendasTam() {
        return this.vendasTam;
    }
    
    public void setVendasTam(VendasTam vendasTam) {
        this.vendasTam = vendasTam;
    }

    
    @Column(name="quantidadeProduto_tam", nullable=false, length=20)
    public String getQuantidadeProdutoTam() {
        return this.quantidadeProdutoTam;
    }
    
    public void setQuantidadeProdutoTam(String quantidadeProdutoTam) {
        this.quantidadeProdutoTam = quantidadeProdutoTam;
    }

    
    @Column(name="valorUnitario_tam", nullable=false, length=20)
    public String getValorUnitarioTam() {
        return this.valorUnitarioTam;
    }
    
    public void setValorUnitarioTam(String valorUnitarioTam) {
        this.valorUnitarioTam = valorUnitarioTam;
    }

    
    @Column(name="formaPagamento_tam", nullable=false)
    public int getFormaPagamentoTam() {
        return this.formaPagamentoTam;
    }
    
    public void setFormaPagamentoTam(int formaPagamentoTam) {
        this.formaPagamentoTam = formaPagamentoTam;
    }

    
    @Column(name="desconto_tam", nullable=false, length=20)
    public String getDescontoTam() {
        return this.descontoTam;
    }
    
    public void setDescontoTam(String descontoTam) {
        this.descontoTam = descontoTam;
    }

    
    @Column(name="tipoDesconto_tam", nullable=false, length=20)
    public String getTipoDescontoTam() {
        return this.tipoDescontoTam;
    }
    
    public void setTipoDescontoTam(String tipoDescontoTam) {
        this.tipoDescontoTam = tipoDescontoTam;
    }




}


