package bean;
// Generated Oct 22, 2025 11:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasTam generated by hbm2java
 */
@Entity
@Table(name="vendas_tam"
    ,catalog="db_thais_oliveira"
)
public class VendasTam  implements java.io.Serializable {


     private int idvendaTam;
     private ClienteTam clienteTam;
     private UsuariosTam usuariosTam;
     private Date dataVendaTam;
     private String tipoVendaTam;
     private int formaPagamentoTam;
     private String horaVendaTam;
     private String observacoesVendaTam;
 

    public VendasTam() {
    }

	
    public VendasTam(int idvendaTam, ClienteTam clienteTam, UsuariosTam usuariosTam, Date dataVendaTam, String tipoVendaTam, int formaPagamentoTam, String horaVendaTam, String observacoesVendaTam) {
        this.idvendaTam = idvendaTam;
        this.clienteTam = clienteTam;
        this.usuariosTam = usuariosTam;
        this.dataVendaTam = dataVendaTam;
        this.tipoVendaTam = tipoVendaTam;
        this.formaPagamentoTam = formaPagamentoTam;
        this.horaVendaTam = horaVendaTam;
        this.observacoesVendaTam = observacoesVendaTam;
    }

   
     @Id 

    
    @Column(name="idvenda_tam", unique=true, nullable=false)
    public int getIdvendaTam() {
        return this.idvendaTam;
    }
    
    public void setIdvendaTam(int idvendaTam) {
        this.idvendaTam = idvendaTam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_venda_cliente_tam", nullable=false)
    public ClienteTam getClienteTam() {
        return this.clienteTam;
    }
    
    public void setClienteTam(ClienteTam clienteTam) {
        this.clienteTam = clienteTam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_venda_usuario", nullable=false)
    public UsuariosTam getUsuariosTam() {
        return this.usuariosTam;
    }
    
    public void setUsuariosTam(UsuariosTam usuariosTam) {
        this.usuariosTam = usuariosTam;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVenda_tam", nullable=false, length=10)
    public Date getDataVendaTam() {
        return this.dataVendaTam;
    }
    
    public void setDataVendaTam(Date dataVendaTam) {
        this.dataVendaTam = dataVendaTam;
    }

    
    @Column(name="tipoVenda_tam", nullable=false, length=45)
    public String getTipoVendaTam() {
        return this.tipoVendaTam;
    }
    
    public void setTipoVendaTam(String tipoVendaTam) {
        this.tipoVendaTam = tipoVendaTam;
    }

    
    @Column(name="formaPagamento_tam", nullable=false)
    public int getFormaPagamentoTam() {
        return this.formaPagamentoTam;
    }
    
    public void setFormaPagamentoTam(int formaPagamentoTam) {
        this.formaPagamentoTam = formaPagamentoTam;
    }

    
    @Column(name="horaVenda_tam", nullable=false, length=10)
    public String getHoraVendaTam() {
        return this.horaVendaTam;
    }
    
    public void setHoraVendaTam(String horaVendaTam) {
        this.horaVendaTam = horaVendaTam;
    }

    
    @Column(name="observacoesVenda_tam", nullable=false, length=50)
    public String getObservacoesVendaTam() {
        return this.observacoesVendaTam;
    }
    
    public void setObservacoesVendaTam(String observacoesVendaTam) {
        this.observacoesVendaTam = observacoesVendaTam;
    }






}


